name: coronavirus_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^0.6.0
  meta: ^1.1.6
  sprintf: "^4.0.0"
  uuid: "2.0.1"
  flutter_svg: ^0.14.2
  google_maps_flutter: ^0.5.21+15
  dotted_border: ^1.0.4
  charts_flutter: ^0.8.1
  # Bloc
  flutter_bloc: ^3.1.0
  dio: 3.0.9
  retrofit_generator: 1.3.7+6
  build_runner: 1.10.1
  json_serializable: 3.4.1

  retrofit: any
  json_annotation: any
  carousel_slider: ^1.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: font/Roboto-Regular.ttf
          weight: 400
        - asset: font/Roboto-Medium.ttf
          weight: 500
        - asset: font/Roboto-Bold.ttf
          weight: 600
  assets:
    - assets/